spring:
  application:
    name: collector
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8080

logging:
  level:
    ru.yandex.practicum.collector: DEBUG
    org.apache.kafka: WARN
    org.springframework.kafka: DEBUG