spring:
  application:
    name: collector
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        spring.json.add.type.headers: false

grpc:
  server:
    port: 9090

server:
  port: 8080

logging:
  level:
    ru.yandex.practicum.collector: DEBUG
    org.apache.kafka: WARN
    org.springframework.kafka: DEBUG