server:
  port: 8082

spring:
  application:
    name: analyzer

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      negotiation-type: plaintext

logging:
  level:
    ru.yandex.practicum.analyzer: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: WARN