syntax = "proto3";

package telemetry.service.collector;

import "telemetry/messages/sensor_event.proto";
import "telemetry/messages/hub_event.proto";

option java_multiple_files = false;
option java_package = "ru.yandex.practicum.grpc.telemetry.collector";

service CollectorController {
  rpc CollectSensorEvent(telemetry.message.event.SensorEventProto) returns (CollectResponse);
  rpc CollectHubEvent(telemetry.message.event.HubEventProto) returns (CollectResponse);
}

message CollectResponse {
  bool success = 1;
  string message = 2;
}